name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ununtu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print another greeting
        run: echo "Hello Swapnil!"
